### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by xiexianbin** [venusteam/codegen#2]
如何使用？

**Comment by SoftwareKing** [comment]
http://start.springcloud.cn/

**Comment by xiexianbin** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Mar 02 10:21:15 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
Key [applicationType] isn't found in properties

**Comment by CraKeyBoy** [comment]
生成报错了。。看看吧
